#!/bin/bash
# Execute profiling and tracing jobs on K
# from designated directories
#
# 2015-2016 Bryzgalov Peter @ RIKEN AICS


source ./config.sh

# Set to nonzero to run Score-P instrumented jobs
pause=15

read -rd '' usage << EOF
Execute profiling and tracing jobs on K
from designated directories.
(C) 2015-2016 Bryzgalov Peter @ RIKEN AICS

directories: $(echo "${directs[*]}")
Score-P is $( if [ -z "$scorep" ];then echo "not "; fi)used.
EOF

echo "$usage"

read -r -p "This will run a set of test jobs for testing TAU. Continue? [Y/n] " input
case $input in
    [yY][eE][sS]|[yY])
        echo "Starting..."
    ;;
    *)
        echo "Bye!"
        exit 0
    ;;
esac


function containsElement {
    local e
    for e in "${@:2}"; do [[ "$e" == "$1" ]] && echo "1"; done
    echo ""
}


for dir in ${directs[@]}; do
    cd $dir
    mapfile -t jobfiles <<< "$(ls job.*.sh)"
    for jobfile in "${jobfiles[@]}"; do
        echo "Run $dir/$jobfile"
        pjsub $jobfile
        sleep $pause
    done
    cd ..
done
